config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:index, :new, :create, :show] do
    resources :comentarios, only: [:new, :create]
  end

  root to: "posts#index"

  resources :clientes, except: [:destroy, :index, :show]
  resources :funcionarios
  devise_for :users, :skip => [:registrations] , controllers: {
      sessions: 'users/sessions'
  }

  %w(404 422 500).each do |code|
    get code, :to => "erros#show", :code => code
  end

  get '*unmatched_route', to: 'application#raise_not_found'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  validates :nome, :email, :usuario, :descricao, presence: {message: "Campo deve ser preenchido corretamente"}
  validates :nome, length: {maximum: 100, message: "ultrapassou limite de caracteres"}
  validates :descricao, length: {maximum: 200, message: "ultrapassou limite de caracteres"}
  validates :email, uniqueness: {case_sensitive: false, message: "já cadastrado"}
  validates :usuario, length: {maximum: 15, message: "ultrapassou limite de caracteres"}, uniqueness: {case_sensitive: false, message: "já cadastrado"}
  validates :senha, length: {in: 6..12, message: "Deve ter de 6 a 12 caracteres"}
  validates :senha, presence: true, on: :create
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update]
  before_action :permit?, only: [:edit, :update]
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]

  # GET /clientes/new
  def new
    @cliente = Cliente.new
    render layout: 'login'
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)
    respond_to do |format|
      if @cliente.save

        user = User.create(
            email: cliente_params["email"], username: cliente_params["usuario"],
            clientes_id: @cliente.id, manager: true, password: cliente_params["senha"]
        )

        sign_in(user, scope: :user)
        format.html { redirect_to funcionarios_path, notice: 'Cliente criado com sucesso' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, layout: 'login' }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to funcionarios_path, notice: 'Cliente alterado com sucesso' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    def permit?
      if @cliente.id != current_user.clientes_id
        redirect_to funcionarios_path
      end
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nome, :email, :descricao, :usuario, :senha)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/edit.html.erb
<%= form_with(model: @cliente, local: true) do |form| %>
  <h2>Alterar Cliente</h2>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "erros") %> <br/> Verifique os erros abaixo:</h2>

      <ul>
        <% @cliente.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group has-error">
    <%= form.label :nome %>
    <%= form.text_field :nome, class: 'form-control', required: true  %>
  </div>

  <div class="form-group has-error">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control', required: true  %>
  </div>

  <div class="form-group has-error">
    <%= form.label 'Descrição da empresa' %>
    <%= form.text_field :descricao, class: 'form-control', required: true  %>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar', class: "btn btn-danger btn-lg btn-block" %>
  </div>
<% end %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nome %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.descricao %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<div class="login-form">
  <%= form_with(model: @cliente, local: true) do |form| %>
    <h2>Cadastrar Cliente</h2>
    <% if @cliente.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@cliente.errors.count, "erros") %> <br/> Verifique os erros abaixo:</h2>

        <ul>
          <% @cliente.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group has-error">
      <%= form.label :nome %>
      <%= form.text_field :nome, class: 'form-control', required: true  %>
    </div>

    <div class="form-group has-error">
      <%= form.label :email %>
      <%= form.email_field :email, class: 'form-control', required: true  %>
    </div>

    <div class="form-group has-error">
      <%= form.label 'Descrição da empresa' %>
      <%= form.text_field :descricao, class: 'form-control', required: true  %>
    </div>

    <div class="form-group has-error">
      <%= form.label 'Usuário' %>
      <%= form.text_field :usuario, class: 'form-control', required: true  %>
    </div>

    <div class="form-group has-error">
      <%= form.label 'Senha' %>
      <%= form.password_field :senha, autocomplete: "current-password", class: "form-control", required: true  %>
    </div>

    <div class="actions">
      <%= form.submit 'Salvar', class: "btn btn-secondary btn-lg btn-block" %>
    </div>
  <% end %>
</div>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @cliente.descricao %>
</p>
<%= current_user.id %>
<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>