config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:index, :new, :create, :show] do
    resources :comentarios, only: [:new, :create]
  end

  root to: "posts#index"

  resources :clientes, except: [:destroy, :index, :show]
  resources :funcionarios
  devise_for :users, :skip => [:registrations] , controllers: {
      sessions: 'users/sessions'
  }

  %w(404 422 500).each do |code|
    get code, :to => "erros#show", :code => code
  end

  get '*unmatched_route', to: 'application#raise_not_found'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  validates :descricao, length: {maximum: 255, message: 'Não pode ultrapassar 255 caracteres'}
  validates :assunto, length: {maximum: 100, message: 'Não pode ultrapassar 100 caracteres'}

  belongs_to :user
  belongs_to :cliente
  has_many :comentarios
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :new, :create]
  before_action :set_cliente, only: [:index, :new, :create, :show]
  before_action :permit?, only: [:show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(cliente_id: @cliente)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.cliente_id = @cliente
    @post.user_id = @user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = current_user.id
    end

    def set_cliente
      @cliente = current_user.clientes_id
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def permit?
      if @post.cliente_id != @cliente
        redirect_to posts_path
      end
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:descricao, :assunto, :clientes_id, :users_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<%= link_to 'Postar Algo', new_post_path %>
<% @posts.each do |post| %>
  <div class="row">
    <div class="card" style="width: 100%; margin-top: 10px;">
      <div class="card-header">
        <%= post.assunto %>
        <%= link_to 'Visualizar', post, class: "float-right" %>
        <%= link_to 'Comentar', new_post_comentario_path(post), class: "float-right", style: 'margin-right: 10px;' %>
      </div>
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <p><%= post.descricao %></p>
          <footer class="blockquote-footer"><%= post.user.username %> <cite title="Título da fonte"><%= date(post.created_at)%> - <%= post.comentarios.size %> comentários</cite></footer>
        </blockquote>
      </div>
    </div>
  </div>
<% end %>
<% if @posts.empty? %>
 <h4>Nenhuma postagem foi criada</h4>
<% end %>

app/views/posts/new.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <h2>Cadastrar Postagem</h2>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "erros") %> <br/> Verifique os erros abaixo:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group has-error">
    <%= form.label "Assunto" %>
    <%= form.text_field :assunto, class: 'form-control', required: true  %>
  </div>

  <div class="form-group has-error">
    <%= form.label 'Descrição' %>
    <%= form.text_field :descricao, class: 'form-control', required: true  %>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar', class: "btn btn-danger btn-lg btn-block" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="row">
  <div class="card" style="width: 100%; margin-top: 10px;">
    <div class="card-header">
      <%= @post.assunto %>
      <%= link_to 'Voltar aos posts', posts_path, class: "float-right" %>
      <%= link_to 'Comentar', new_post_comentario_path(@post), class: "float-right", style: 'margin-right: 10px;' %>
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p><%= @post.descricao %></p>
        <footer class="blockquote-footer"><%= @post.user.username %> <cite title="Título da fonte"><%= date(@post.created_at)%> </cite></footer>
      </blockquote>
    </div>
  </div>
</div>
<h4 style="margin-top: 20px;">Comentários</h4>
<% @post.comentarios.each do |comentario| %>
  <div>
    <blockquote class="blockquote mb-0">
      <p><%= comentario.descricao %></p>
      <footer class="blockquote-footer"><%= comentario.user.username %> <cite title="Título da fonte"><%= date(comentario.created_at)%> </cite></footer>
    </blockquote>
  </div>
  <hr>
<% end %>