config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:index, :new, :create, :show] do
    resources :comentarios, only: [:new, :create]
  end

  root to: "posts#index"

  resources :clientes, except: [:destroy, :index, :show]
  resources :funcionarios
  devise_for :users, :skip => [:registrations] , controllers: {
      sessions: 'users/sessions'
  }

  %w(404 422 500).each do |code|
    get code, :to => "erros#show", :code => code
  end

  get '*unmatched_route', to: 'application#raise_not_found'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  respond_to :html
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :set_cliente, only: [:index, :new, :create, :edit, :update]
  before_action :permit?, only: [:new, :create, :index]
  before_action :permit_edit?, only: [:edit, :update]

  def index
    @users = User.where(clientes_id: @cliente, manager: false)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(funcionario_params)
    @user.clientes_id = @cliente

    respond_to do |format|
      if @user.save
        format.html { redirect_to funcionarios_path, notice: 'Usuário Cadastrado com sucesso' }
        format.json { render :index, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(funcionario_params)
        format.html { redirect_to funcionarios_path, notice: 'Usuário alterado com sucesso' }
        format.json { render :index, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_path, notice: 'Usuário excluído com sucesso' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_cliente
    @cliente = current_user.clientes_id
  end

  def permit?
    if @cliente != current_user.clientes_id
      redirect_to funcionarios_path
    end
  end

  def permit_edit?
    if @user.clientes_id != current_user.clientes_id
      redirect_to funcionarios_path
    end
  end

  def funcionario_params
    params.require(:user).permit(:email, :password, :username).merge(manager: false)
  end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/edit.html.erb
<%= form_with(scope: :user, local: true, url: funcionario_path(@user), method: :put) do |form| %>
  <h2>Cadastrar Usuário</h2>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>Verifique os erros abaixo</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group has-error">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control', required: true  %>
  </div>

  <div class="form-group has-error">
    <%= form.label 'Usuário' %>
    <%= form.text_field :username, class: 'form-control', required: true  %>
  </div>

  <div class="form-group has-error">
    <%= form.label 'Senha' %>
    <%= form.password_field :password, autocomplete: "current-password", class: "form-control", required: true  %>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar', class: "btn btn-danger btn-lg btn-block" %>
  </div>
<% end %>

app/views/funcionarios/index.html.erb
<%= link_to 'Novo usuário', new_funcionario_path %>
<div class="table-responsive-md">
  <table class="table">
    <h2>Lista de usuários</h2>
    <thead>
      <tr>
        <th colspan="2">Ações</th>
        <th scope="col">Email</th>
        <th scope="col">Usuario</th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="text-right"><%= link_to 'Alterar', edit_funcionario_path(user) %></td>
        <td class="text-right"><%= link_to 'Excluir', funcionario_path(user), method: :delete, data: { confirm: 'Tem certeza?' } %></td>
        <td class="text-right"><%= user.email %></td>
        <td class="text-right"><%= user.username %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/funcionarios/new.html.erb
<%= form_with(scope: :user, local: true, url: funcionarios_path) do |form| %>
  <h2>Cadastrar Usuário</h2>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>Verifique os erros abaixo</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group has-error">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control', required: true  %>
  </div>

  <div class="form-group has-error">
    <%= form.label 'Usuário' %>
    <%= form.text_field :username, class: 'form-control', required: true  %>
  </div>

  <div class="form-group has-error">
    <%= form.label 'Senha' %>
    <%= form.password_field :password, autocomplete: "current-password", class: "form-control", required: true  %>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar', class: "btn btn-danger btn-lg btn-block" %>
  </div>
<% end %>