config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:index, :new, :create, :show] do
    resources :comentarios, only: [:new, :create]
  end

  root to: "posts#index"

  resources :clientes, except: [:destroy, :index, :show]
  resources :funcionarios
  devise_for :users, :skip => [:registrations] , controllers: {
      sessions: 'users/sessions'
  }

  %w(404 422 500).each do |code|
    get code, :to => "erros#show", :code => code
  end

  get '*unmatched_route', to: 'application#raise_not_found'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestaoEmpresa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand navbar-dark bg-danger"> <a href="#menu-toggle" id="menu-toggle" class="navbar-brand"><span class="navbar-toggler-icon"></span></a> <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
    <div class="collapse navbar-collapse" id="navbarsExample02">
      <form class="form-inline my-2 my-md-0"> </form>
    </div>
  </nav>
  <div id="wrapper" class="toggled">
    <!-- Sidebar -->
    <div id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <li class="sidebar-brand"> <a href="#"> Gestão Empresa </a> </li>
        <% if current_user.manager %>
          <li> <%= link_to 'Funcionários', funcionarios_path %></li>
          <li> <%= link_to 'Editar Dados do Cliente', edit_cliente_path(Cliente.find(current_user.clientes_id)) %></li>
        <% end %>
        <li> <%= link_to 'Postagens', posts_path %></li>
        <li><%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
      </ul>
    </div> <!-- /#sidebar-wrapper -->
    <!-- Page Content -->
    <div id="page-content-wrapper">
      <div class="container-fluid">
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </div>
    </div> <!-- /#page-content-wrapper -->
  </div> <!-- /#wrapper -->
  </body>
</html>
<script>
    $(function(){
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });

        $(window).resize(function(e) {
            if($(window).width()<=768){
                $("#wrapper").removeClass("toggled");
            }else{
                $("#wrapper").addClass("toggled");
            }
        });
    });

</script>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestão Empresa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="body-login">
    <%= yield %>
  </body>
</html>